### ISSUE TITLE
Inquiries regarding your intriguing research

### ISSUE THREAD

**Issue by yejinc00** [JaesungHuh/SimpleDiarization#2]
Hello, as a student interested in the field of speech, first of all, thank you for your wonderful research.
I was also surprised by the very good diarization performance for arbitrary data on YouTube.

After using it with interest, I have a question as below and leave it on the issue.

- Diarization was not successful for audio files whose sample rate is not 16000.
Is it because most of the audio files used for the learning dataset have a sample rate of 16000?
(I compared the same audio file with different sample rates)

- I wonder if you have any further research plans on diarization in the section where the utterances overlap.

Thank you for your wonderful research. Have a good day😊

**Comment by JaesungHuh** [comment]
Hi. Thanks for the comment. Glad to hear that you are using this repo well.

Further to your questions:
(1) Yes, it is. Speaker model and VAD are only trained with 16kHz PCM 16bit audio files . I think I should make this clear in the README. Thanks for pointing this out.

(2) Unfortunately, I don't have any plans on diarization with overlapping speech. This repo was originally for the [AutoAD](https://www.robots.ox.ac.uk/~vgg/research/autoad/) project and baseline for [VoxSRC workshop](http://mm.kaist.ac.kr/datasets/voxceleb/voxsrc/competition2022.html).

There are quite a few good research papers which address this problem. (ex - [this](https://arxiv.org/pdf/1909.06247.pdf), [this](http://mm.kaist.ac.kr/datasets/voxceleb/voxsrc/data_workshop_2022/reports/DKU-SMIIP_report.pdf) and [this](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9053096)) You could check on these.

Have a nice weekend :)
