### ISSUE TITLE
Does it support direct Python calls?

### ISSUE THREAD

**Issue by 12915494174** [JaesungHuh/SimpleDiarization#4]
I need to apply it to the code now. Do you have any encapsulated methods that can be directly called? If so, I haven't found any relevant documents, please give me some tips.

**Comment by JaesungHuh** [comment]
Hi. 
Currently, I did not implement any encapsulated methods yet.
As you can see in https://github.com/JaesungHuh/SimpleDiarization/blob/main/main.py. 
You could use it as 
```
# Call the diarization module first with proper config dict cfg
diarize_module = DiarizationModule(cfg)
# Run diarization module with wav_file
sys_rttm = diarize_module.run(wav_file, wav_file.replace('.wav', '.rttm'), "")
```

**Comment by 12915494174** [comment]
> 你好。 目前，我还没有实现任何封装方法。正如您在https://github.com/JaesungHuh/SimpleDiarization/blob/main/main.py 中看到的。 你可以用它作为[](https://github.com/JaesungHuh/SimpleDiarization/blob/main/main.py)
> 
> ```
> # Call the diarization module first with proper config dict cfg
> diarize_module = DiarizationModule(cfg)
> # Run diarization module with wav_file
> sys_rttm = diarize_module.run(wav_file, wav_file.replace('.wav', '.rttm'), "")
> ```

ok, thank you.
